name: Test
on: [push, pull_request]

jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    container: spack/centos7
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install modules
        run: sudo apt-get install -y environment-modules
      - name: install extension
        run: python test/addextension.py $(spack config --scope site edit config --print-file) $(pwd)
      - name: run tests
        run: bash test/run.sh
