name: Test
on: [push, pull_request]

jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    container: spack/centos7
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install extension
        run: bash test/addextension.sh
      - name: run tests
        run: bash test/run.sh
